/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OperatorFilterRegistry } from "./OperatorFilterRegistry";
export * as factories from "./factories";
export { OperatorFilterRegistry__factory } from "./factories/OperatorFilterRegistry__factory";
