/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155Tradable } from "./ERC1155Tradable";
export type { ProxyRegistry } from "./ProxyRegistry";
