/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type {
  OperatorFilterRegistry,
  OperatorFilterRegistryInterface,
} from "../OperatorFilterRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
    ],
    name: "isOperatorFiltered",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
    ],
    name: "registerOperator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
    ],
    name: "unregisterOperator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061014f806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806309e2688a146100465780633682a4501461008657806396115bc2146100ba575b600080fd5b6100726100543660046100e9565b6001600160a01b031660009081526020819052604090205460ff1690565b604051901515815260200160405180910390f35b6100b86100943660046100e9565b6001600160a01b03166000908152602081905260409020805460ff19166001179055565b005b6100b86100c83660046100e9565b6001600160a01b03166000908152602081905260409020805460ff19169055565b6000602082840312156100fb57600080fd5b81356001600160a01b038116811461011257600080fd5b939250505056fea26469706673582212205784fedb787e6a37e987c4dbf954c6aa792ab908a8f42cb376afc11a77371a6164736f6c63430008110033";

type OperatorFilterRegistryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: OperatorFilterRegistryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class OperatorFilterRegistry__factory extends ContractFactory {
  constructor(...args: OperatorFilterRegistryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      OperatorFilterRegistry & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): OperatorFilterRegistry__factory {
    return super.connect(runner) as OperatorFilterRegistry__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): OperatorFilterRegistryInterface {
    return new Interface(_abi) as OperatorFilterRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): OperatorFilterRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as OperatorFilterRegistry;
  }
}
