/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockProxyRegistry } from "./MockProxyRegistry";
export type { TestForReentrancyAttack } from "./TestForReentrancyAttack";
