/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../common";

export interface LootBoxRandomnessInterface extends Interface {
  getEvent(nameOrSignatureOrTopic: "LootBoxOpened" | "Warning"): EventFragment;
}

export namespace LootBoxOpenedEvent {
  export type InputTuple = [
    optionId: BigNumberish,
    buyer: AddressLike,
    boxesPurchased: BigNumberish,
    itemsMinted: BigNumberish
  ];
  export type OutputTuple = [
    optionId: bigint,
    buyer: string,
    boxesPurchased: bigint,
    itemsMinted: bigint
  ];
  export interface OutputObject {
    optionId: bigint;
    buyer: string;
    boxesPurchased: bigint;
    itemsMinted: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WarningEvent {
  export type InputTuple = [message: string, account: AddressLike];
  export type OutputTuple = [message: string, account: string];
  export interface OutputObject {
    message: string;
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LootBoxRandomness extends BaseContract {
  connect(runner?: ContractRunner | null): LootBoxRandomness;
  waitForDeployment(): Promise<this>;

  interface: LootBoxRandomnessInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "LootBoxOpened"
  ): TypedContractEvent<
    LootBoxOpenedEvent.InputTuple,
    LootBoxOpenedEvent.OutputTuple,
    LootBoxOpenedEvent.OutputObject
  >;
  getEvent(
    key: "Warning"
  ): TypedContractEvent<
    WarningEvent.InputTuple,
    WarningEvent.OutputTuple,
    WarningEvent.OutputObject
  >;

  filters: {
    "LootBoxOpened(uint256,address,uint256,uint256)": TypedContractEvent<
      LootBoxOpenedEvent.InputTuple,
      LootBoxOpenedEvent.OutputTuple,
      LootBoxOpenedEvent.OutputObject
    >;
    LootBoxOpened: TypedContractEvent<
      LootBoxOpenedEvent.InputTuple,
      LootBoxOpenedEvent.OutputTuple,
      LootBoxOpenedEvent.OutputObject
    >;

    "Warning(string,address)": TypedContractEvent<
      WarningEvent.InputTuple,
      WarningEvent.OutputTuple,
      WarningEvent.OutputObject
    >;
    Warning: TypedContractEvent<
      WarningEvent.InputTuple,
      WarningEvent.OutputTuple,
      WarningEvent.OutputObject
    >;
  };
}
