/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155Tradable__factory } from "./ERC1155Tradable__factory";
export { ProxyRegistry__factory } from "./ProxyRegistry__factory";
