/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc1155TradableSol from "./ERC1155Tradable.sol";
export type { erc1155TradableSol };
import type * as erc721TradableSol from "./ERC721Tradable.sol";
export type { erc721TradableSol };
import type * as iFactoryErc1155Sol from "./IFactoryERC1155.sol";
export type { iFactoryErc1155Sol };
import type * as iFactoryErc721Sol from "./IFactoryERC721.sol";
export type { iFactoryErc721Sol };
import type * as lootBoxRandomnessSol from "./LootBoxRandomness.sol";
export type { lootBoxRandomnessSol };
import type * as common from "./common";
export type { common };
import type * as test from "./test";
export type { test };
export type { Creature } from "./Creature";
export type { CreatureAccessory } from "./CreatureAccessory";
export type { CreatureAccessoryFactory } from "./CreatureAccessoryFactory";
export type { CreatureAccessoryLootBox } from "./CreatureAccessoryLootBox";
export type { CreatureFactory } from "./CreatureFactory";
export type { CreatureLootBox } from "./CreatureLootBox";
export type { Migrations } from "./Migrations";
