/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockProxyRegistry__factory } from "./MockProxyRegistry__factory";
export { TestForReentrancyAttack__factory } from "./TestForReentrancyAttack__factory";
